# Generated by Django 5.2.1 on 2025-06-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashReport', '0002_incident_incidentimage_incidenttype_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
