# Generated by Django 5.2.1 on 2025-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashReport', '0005_incident_reporter_name_alter_incident_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='description',
        ),
        migrations.AddField(
            model_name='zone',
            name='level',
            field=models.TextField(blank=True, choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')]),
        ),
    ]
