# Generated by Django 5.2.1 on 2025-06-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashReport', '0006_remove_zone_description_zone_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='level',
            field=models.CharField(blank=True, choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')]),
        ),
    ]
