# Generated by Django 5.2.1 on 2025-06-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashReport', '0007_alter_zone_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentimage',
            name='image_incident',
        ),
        migrations.AddField(
            model_name='incidentimage',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='statics/incident_image'),
        ),
    ]
