# Generated by Django 5.2.1 on 2025-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashReport', '0008_remove_incidentimage_image_incident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='level',
            field=models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], max_length=10),
        ),
    ]
